version: '3'

services:

  mariadb:
    container_name: mariadb
    env_file: .env
    networks:
      - docker_network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  
  nginx:
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
     - docker_network
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - docker_network
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/hspriet/data/wordpress'
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/hspriet/data/mariadb'
      o: bind

networks:
    docker_network:
      driver: bridge
